### ISSUE TITLE
fortigate_os_backdoor bug

### ISSUE THREAD

**Issue by glezo1** [threat9/routersploit#212]
I've come to realize that the module fortigate_os_backdoor hangs after offering a prompt. 
I have tested this behaviour on several vulnerable routers.

**Comment by jabedude** [comment]
Can you give screenshots of your rsf prompt when the module hangs?
Also screenshot your router's firmware version as well please.

**Comment by glezo1** [comment]
of course!

I manually generate the hash challenge, connect by ssh, and it works.


[cid:30d53714-f20a-4ac3-ad49-7600c1e510a2]

yet, as you can see in the left picture, the prompt will hang, no matter the command you type.
As well as "echo holi", I tried "get system status"; which is a command the cli would understand and execute, but it hangs as well.

Thank you!
________________________________
De: Joshua Abraham <notifications@github.com>
Enviado: domingo, 19 de marzo de 2017 20:52
Para: reverse-shell/routersploit
Cc: glezo1; Author
Asunto: Re: [reverse-shell/routersploit] fortigate_os_backdoor bug (#212)


Can you give screenshots of your rsf prompt when the module hangs?
Also screenshot your router's firmware version as well please.

**Comment by lucyoa** [comment]
What is your fortigate version?

I tried on my vm appliance "Version: Fortigate-VM v4.0,build0513,120130 (MR3 Patch 5)" and it works flawlessly. I am able to issue commands:
<img width="1032" alt="fortigate" src="https://cloud.githubusercontent.com/assets/5042653/24085539/8d5a1582-0cfe-11e7-8a04-16b04e98f16c.png">

**Comment by glezo1** [comment]
Hi @lucyoa 
I'm sorry for the delay, quite busy at work.
It seems to be v5.0, build3608:
![fortigate_bug](https://cloud.githubusercontent.com/assets/6279737/24324545/b2b8dcc6-1188-11e7-99ad-bb1f0fc2cda1.png)

**Comment by lucyoa** [comment]
Still cannot reproduce this behaviour, have you tried using routersploit on different platform? Linux/OSX/Windows? Maybe the issue is related to ssh interactive implementation

**Comment by fwkz** [comment]
@glezo1 ping

**Comment by glezo1** [comment]
pong!
I used kali 2 x86
