### ISSUE TITLE
Problems with ssh_bruteforce

### ISSUE THREAD

**Issue by karserasl** [threat9/routersploit#318]
I use kali and tried both git and repos ones.

I have putted the correct pass on the dictionary. Also tried with just 1 worker.
My router is accessible through ssh. Linksys e2000 with Tomato Shibby firmware

> Exception in thread worker-2:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/root/routersploit/routersploit/modules/creds/ssh_bruteforce.py", line 102, in target_function
>     ssh.connect(self.target, int(self.port), timeout=5, username=user, password=password)
>   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 305, in connect
>     retry_on_signal(lambda: sock.connect(addr))
>   File "/usr/lib/python2.7/dist-packages/paramiko/util.py", line 269, in retry_on_signal
>     return function()
>   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 305, in <lambda>
>     retry_on_signal(lambda: sock.connect(addr))
>   File "/usr/lib/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> timeout: timed out
> 
> Exception in thread worker-4:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/root/routersploit/routersploit/modules/creds/ssh_bruteforce.py", line 102, in target_function
>     ssh.connect(self.target, int(self.port), timeout=5, username=user, password=password)
>   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 305, in connect
>     retry_on_signal(lambda: sock.connect(addr))
>   File "/usr/lib/python2.7/dist-packages/paramiko/util.py", line 269, in retry_on_signal
>     return function()
>   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 305, in <lambda>
>     retry_on_signal(lambda: sock.connect(addr))
>   File "/usr/lib/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> timeout: timed out
> 
> Exception in thread worker-3:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/root/routersploit/routersploit/modules/creds/ssh_bruteforce.py", line 102, in target_function
>     ssh.connect(self.target, int(self.port), timeout=5, username=user, password=password)
>   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 305, in connect
>     retry_on_signal(lambda: sock.connect(addr))
>   File "/usr/lib/python2.7/dist-packages/paramiko/util.py", line 269, in retry_on_signal
>     return function()
>   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 305, in <lambda>
>     retry_on_signal(lambda: sock.connect(addr))
>   File "/usr/lib/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> timeout: timed out
> 
> Exception in thread worker-5:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/root/routersploit/routersploit/modules/creds/ssh_bruteforce.py", line 102, in target_function
>     ssh.connect(self.target, int(self.port), timeout=5, username=user, password=password)
>   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 305, in connect
>     retry_on_signal(lambda: sock.connect(addr))
>   File "/usr/lib/python2.7/dist-packages/paramiko/util.py", line 269, in retry_on_signal
>     return function()
>   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 305, in <lambda>
>     retry_on_signal(lambda: sock.connect(addr))
>   File "/usr/lib/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> timeout: timed out
> 
> Exception in thread worker-6:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/root/routersploit/routersploit/modules/creds/ssh_bruteforce.py", line 102, in target_function
>     ssh.connect(self.target, int(self.port), timeout=5, username=user, password=password)
>   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 305, in connect
>     retry_on_signal(lambda: sock.connect(addr))
>   File "/usr/lib/python2.7/dist-packages/paramiko/util.py", line 269, in retry_on_signal
>     return function()
>   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 305, in <lambda>
>     retry_on_signal(lambda: sock.connect(addr))
>   File "/usr/lib/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> timeout: timed out
> 
> Exception in thread worker-7:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/root/routersploit/routersploit/modules/creds/ssh_bruteforce.py", line 102, in target_function
>     ssh.connect(self.target, int(self.port), timeout=5, username=user, password=password)
>   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 305, in connect
>     retry_on_signal(lambda: sock.connect(addr))
>   File "/usr/lib/python2.7/dist-packages/paramiko/util.py", line 269, in retry_on_signal
>     return function()
>   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 305, in <lambda>
>     retry_on_signal(lambda: sock.connect(addr))
>   File "/usr/lib/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> timeout: timed out
> 
> Exception in thread worker-1:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/root/routersploit/routersploit/modules/creds/ssh_bruteforce.py", line 102, in target_function
>     ssh.connect(self.target, int(self.port), timeout=5, username=user, password=password)
>   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 305, in connect
>     retry_on_signal(lambda: sock.connect(addr))
>   File "/usr/lib/python2.7/dist-packages/paramiko/util.py", line 269, in retry_on_signal
>     return function()
>   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 305, in <lambda>
>     retry_on_signal(lambda: sock.connect(addr))
>   File "/usr/lib/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> timeout: timed out
> 
> Exception in thread worker-0:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/root/routersploit/routersploit/modules/creds/ssh_bruteforce.py", line 102, in target_function
>     ssh.connect(self.target, int(self.port), timeout=5, username=user, password=password)
>   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 305, in connect
>     retry_on_signal(lambda: sock.connect(addr))
>   File "/usr/lib/python2.7/dist-packages/paramiko/util.py", line 269, in retry_on_signal
>     return function()
>   File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 305, in <lambda>
>     retry_on_signal(lambda: sock.connect(addr))
>   File "/usr/lib/python2.7/socket.py", line 228, in meth
>     return getattr(self._sock,name)(*args)
> timeout: timed out
> 
> [*] Elapsed time:  8.0765080452 seconds
> [-] Credentials not found
>

**Comment by 0BuRner** [comment]
It's probably a DDoS/Bruteforce protection =)

**Comment by lucyoa** [comment]
It should be fixed.
