### ISSUE TITLE
frequent git release tags

### ISSUE THREAD

**Issue by anthraxx** [threat9/routersploit#417]
Hi,

I have noticed that since 2016 there were not git releases anymore. Would it be possible to start semi frequent releases again? This would aid packaging routersploit for distro packages.
No special handling or stuff expected, just regular tags like metasploit f.e.

**Comment by lucyoa** [comment]
We have implemented this process. There will be new release every 2 weeks (monday) - tagged release with description of recent changes.

**Comment by anthraxx** [comment]
@lucyoa this is super awesome :tada: 
thanks a lot, very much appreciated

**Comment by anthraxx** [comment]
@lucyoa can we get another release? :cat:
