### ISSUE TITLE
migrate from pycrypto to pycryptodome

### ISSUE THREAD

**Issue by blshkv** [threat9/routersploit#450]
https://blog.sqreen.io/stop-using-pycrypto-use-pycryptodome/

pycrypto is old, not supported and vulnerable. Please migrate to a better suported library

**Comment by blshkv** [comment]
you have simple change dependency without any code change and this is fine.
However, the new requirment ```pycryptodome==3.6.6``` is too strict. Please remove version restriction or use ```>=``` if this is really required (I'm sure it is not required)

**Comment by iamleot** [comment]
Hello 0BuRner,

0BuRner writes:
> Why is the benefit or using >= except sparing some kB ?
> If you install in a new env, I don't see any problem.
> It's seems even better to me as this version has been tested with routersploit so there is not risk to use a version which might not work for any reason and break the tests

At least for package systems (speaking about pkgsrc but I guess
that other package systems also do that), this usually means that
`setup.py' will need to be patched and the patch should be adjusted
every time the Python package is updated.

IME most of the times the `==' or even the `<=...' version restrictions
are just too strict (i.e. most of the time if a different newer
version of a dependency is used the package still works).

**Comment by iamleot** [comment]
Marcin Bury writes:
> Closed #450 via #504.

Thank you Marcin!
