### ISSUE TITLE
No module named 'future'

### ISSUE THREAD

**Issue by Tommrodrigues** [threat9/routersploit#463]
Hey there, 

I'm trying to run routersploit for the first time on my Mac and after having installed all the respective dependencies, I keep hitting the same problem when trying to run the `python3 rsf.py` command. I receive the error:

```
Traceback (most recent call last):
  File "rsf.py", line 10, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/Users/tommyrodrigues/routersploit/routersploit/interpreter.py", line 10, in <module>
    from future.builtins import input
ModuleNotFoundError: No module named 'future'
```

After having fiddled around for a while, I googled the error to find someone who had a similar problem [here](https://github.com/ArduPilot/pymavlink/issues/25) and I ran the recommended command: `pip install future` which seemed to install the module correctly. However, I ran the `python3 rsf.py` command again and received the same error as before. Immediately, I thought that I must not have installed "future" properly so ran the command `pip install future` again but received the response:

```
Requirement already satisfied: future in /Library/Python/2.7/site-packages (0.16.0)
```

Any guidance would be more than helpful! 
(By the way, I installed Python 3 with Homebrew as before this, I was receiving an error saying that I needed to run the command in a Python 3 environment which makes me think that the mention of 2.7 in the response above means that "future" wasn't installed for Python 3.)

Thank you in advance,

Tom

**Comment by lucyoa** [comment]
You should try `python3 -m pip install -r requirements.txt` (`pip install -r requirements.txt` installs packages for python2.7 in your case)

**Comment by Tommrodrigues** [comment]
Thank you so much! Works perfectly! Silly mistake on my part

**Comment by lucyoa** [comment]
No worries :)

**Comment by Zod20** [comment]
@devoni pip installs for python-2. You need to install for python-3. So do pip3 install future and it will install correct one.

**Comment by paulodib11** [comment]
pls having this problem trying to run routersploit on my kali linux for more than 4days and all to no avail.tried so many command and still no answer so pls i need ur help. @lucyoa  i tried what u said but this is what i got
root@kali:~# python3 -m pip install -r requirements.txt
/usr/bin/python3: No module named pip
root@kali:~# python3 -m pip install future
/usr/bin/python3: No module named pip
root@kali:~# pip3 install future
bash: pip3: command not found
root@kali:~# sudo pip3 install future
sudo: pip3: command not found
root@kali:~# sudo pip3 install future
sudo: pip3: command not found
root@kali:~#

**Comment by paulodib11** [comment]
thoughi am new in this environmet just learning

**Comment by Zod20** [comment]
@paulodib11 install pip first. Google how to install pip for python3.

**Comment by paulodib11** [comment]
found d solution

**Comment by Willim777** [comment]
@Tommrodrigues Hi i have same error could you please help me with that? not sure how to fix that please

**Comment by Tommrodrigues** [comment]
@Willim777 Sure, for me, this worked: `python3 -m pip install -r requirements.txt or python3 -m pip install future`

**Comment by Willim777** [comment]
@Tommrodrigues Thanks buddy sayin same problom on my laptop got it to work  on my Desktop PC im Kinda new in hacking .. Wanted to find out do you Know about any good Keylogger To send and get key strokes back? with port forwarding and beelogger myne giving errors also after i create 1. Thanks alot

**Comment by CyberArmed** [comment]
If using Kali you may need to use the following command:
apt install python3-future

**Comment by xag47** [comment]
thnx CyberArmed

**Comment by khunteebwar** [comment]
> If using Kali you may need to use the following command:
> apt install python3-future

Thank you @CyberArmed, it does work for me on Ubuntu as well.

**Comment by F1uffyGoat** [comment]
I am now posting as F1uffyGoat rather than CyberArmed. Glad to see the fix is helping.

**Comment by bbossola** [comment]
I had the same problem right now but using the docker install:
```
$ docker build -t routersploit .
Sending build context to Docker daemon 5.293 MB
Step 1 : FROM python:3.6
3.6: Pulling from library/python
f626654b7ce4: Pull complete 
28d24f910dc8: Pull complete 
36327fec7dc3: Pull complete 
03647c60cbdf: Pull complete 
ba9389172b7c: Pull complete 
491995ace47c: Pull complete 
0f99b7916295: Pull complete 
8b2822db9209: Pull complete 
ee2a5b5d587f: Pull complete 
cffac3aef079: Pull complete 
8eb95223346f: Pull complete 
559d91095dce: Pull complete 
3a8b7232d93c: Pull complete 
3d889902b33c: Pull complete 
902a41a31a1f: Pull complete 
38ae5a701a72: Pull complete 
Digest: sha256:834a6890d8616fd68ac5b8676975c864a286ccfd196fc8d7044c1235f506dba7
Status: Downloaded newer image for python:3.6
 ---> 38ae5a701a72
Step 2 : COPY requirements.txt /tmp/requirements.txt
 ---> f7659f6c3e76
Removing intermediate container 632e55728211
Step 3 : RUN python -m pip install -r /tmp/requirements.txt
 ---> Running in c04e848f0884
Collecting future (from -r /tmp/requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4f2726d2b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/future/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4f2726d9e8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/future/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4f2726d978>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/future/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4f2726de10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/future/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4f2726dc18>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/future/
  Could not find a version that satisfies the requirement future (from -r /tmp/requirements.txt (line 1)) (from versions: )
No matching distribution found for future (from -r /tmp/requirements.txt (line 1))
The command '/bin/sh -c python -m pip install -r /tmp/requirements.txt' returned a non-zero code: 1
````
Any suggestion?

**Comment by bbossola** [comment]
New issue submitted https://github.com/threat9/routersploit/issues/569

**Comment by hajebn** [comment]
👉routersploit
: "Installation on Termux" 
$ apt update && apt upgrade 
$ apt install git 
$ apt install python 
$ apt install python2 
$ git clone https://www.github.com/threat9/routersploit

$ cd routersploit 
$ chmod +x * 

$ pip2 install -r requirements-dev.txt 

$ pip2 install -r requirements.txt 

$ pip2 install future 

$ python rsf.py

👉Error 👇

$ python3 -m pip install -r requirements.txt or

$ python rsf.py 
🔝
 ____________________________

**Comment by Divinefav** [comment]
I have the same problem 
But thanks to you guys i already found a solution through one of the comments 
It's working perfectly

**Comment by emir1408** [comment]
File "/data/data/com.termux/files/home/routersploit/rsf.py", line 10, in <module>                 from routersploit.interpreter import RoutersploitInterpreter

**Comment by char4lie** [comment]
> git clone https://github.com/threat9/routersploit    Cloning into 'routersploit'...
remote: Enumerating objects: 8534, done.                                      remote: Total 8534 (delta 0), reused 0 (delta 0), pack-reused 8534
Receiving objects: 100% (8534/8534), 1.78 MiB | 600.00 KiB/s, done.           Resolving deltas: 100% (6175/6175), done.
u0_a267@localhost ~> cd routersploit                                          u0_a267@localhost ~/routersploit (master)> python3 -m pip install -r requirements.txt                                                                       Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)                                        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 829.2/829.2 KB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done                                      Collecting requests==2.21.0
  Downloading requests-2.21.0-py2.py3-none-any.whl (57 kB)                         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.0/58.0 KB 1.8 MB/s eta 0:00:00
Collecting paramiko                                                             Downloading paramiko-2.11.0-py2.py3-none-any.whl (212 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.9/212.9 KB 2.2 MB/s eta 0:00:00Collecting pysnmp==4.4.6
  Downloading pysnmp-4.4.6-py2.py3-none-any.whl (291 kB)                           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 291.2/291.2 KB 2.9 MB/s eta 0:00:00
Collecting pycryptodome                                                         Downloading pycryptodome-3.14.1.tar.gz (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 2.0 MB/s eta 0:00:00   Preparing metadata (setup.py) ... done
Requirement already satisfied: certifi>=2017.4.17 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from requests==2.21.0->-r requirements.txt (line 2)) (2022.5.18.1)                                                     Collecting idna<2.9,>=2.5
  Downloading idna-2.8-py2.py3-none-any.whl (58 kB)                                ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.6/58.6 KB 1.8 MB/s eta 0:00:00
Collecting urllib3<1.25,>=1.21.1                                                Downloading urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.8/118.8 KB 1.6 MB/s eta 0:00:00Collecting chardet<3.1.0,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)                          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 KB 1.1 MB/s eta 0:00:00
Collecting pysmi                                                                Downloading pysmi-0.3.4-py2.py3-none-any.whl (80 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.0/80.0 KB 854.7 kB/s eta 0:00:00Collecting pycryptodomex
  Downloading pycryptodomex-3.14.1.tar.gz (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 1.1 MB/s eta 0:00:00   Preparing metadata (setup.py) ... done                                      Collecting pyasn1>=0.2.3
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)                            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 KB 263.7 kB/s eta 0:00:00Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)                         Collecting pynacl>=1.0.1
  Downloading PyNaCl-1.5.0.tar.gz (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 705.6 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting bcrypt>=3.1.3
  Downloading bcrypt-3.2.2.tar.gz (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.5/42.5 KB 277.5 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cryptography>=2.5
  Downloading cryptography-37.0.2.tar.gz (585 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 585.4/585.4 KB 460.2 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done

**Comment by char4lie** [comment]
python3 -m pip install -r requirements.txt
