### ISSUE TITLE
Pip3 couldn't be found.

### ISSUE THREAD

**Issue by cr8ckhead** [threat9/routersploit#480]
1:
* RouterSploit Version used: newest
* Operating System and version: kali linux 2.0
* Python Version: python2.7, can't use python3 -m pip install (pip couldn't be found?)
* Python Environment: ???
2:
I can't find a solution anywhere on how to get pip for python 3, I tried EVERYTHING and i can't get pip for python 3 installed.
I use Kali Linux (not Live) and when i go to python3 its only one file.
If somebody could help me with this i would be very pleased!

**Comment by lucyoa** [comment]
Please use newest version of kali `https://www.kali.org/downloads/`.
You can install routersploit there by `apt-get install routersploit`
