### ISSUE TITLE
module not found in kali linux

### ISSUE THREAD

**Issue by devoni** [threat9/routersploit#485]
pip command not found and future module not found either, Using kali linux. have python 3.7.0
.
![image](https://user-images.githubusercontent.com/40850524/42306763-dd326bfc-7ff5-11e8-8b8e-473097a86ec4.png)

tried pip install future. cant find pip. does not even know what it is. thanks in advanced

**Comment by lucyoa** [comment]
Read installation process for kali on Readme.
```
apt-get install python3-pip
git clone https://www.github.com/threat9/routersploit
cd routersploit
python3 -m pip install -r requirements.txt
python3 rsf.py
```

Bluetooth Low Energy support:

```
apt-get install libglib2.0-dev
python3 -m pip install bluepy
python3 rsf.py
```

**Comment by devoni** [comment]
what can i do if i did what you said and pip is still not working?
