### ISSUE TITLE
Using routersploit in scripts

### ISSUE THREAD

**Issue by stevenaldinger** [threat9/routersploit#555]
Edit: Opened a PR for this since it didn't seem supported yet.

## Your Environment

* RouterSploit Version used: 3.4.0
* Operating System and version: Dockerfile (4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 GNU/Linux) -- shouldn't matter for this question
* Python Version: ( `python3 --version` ) 3.6.7
* Python Environment: ( `python3 -m pip freeze` )"
```
asn1crypto==0.24.0
bcrypt==3.1.4
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
cryptography==2.4.2
future==0.17.1
idna==2.7
paramiko==2.4.2
ply==3.11
pyasn1==0.4.4
pycparser==2.19
pycryptodome==3.7.2
pycryptodomex==3.7.2
PyNaCl==1.3.0
pysmi==0.3.2
pysnmp==4.4.6
requests==2.20.1
six==1.11.0
urllib3==1.24.1
```

## Current Behavior

- Does not seem to be a way to script command execution.
- `exec` seemed like the closest lead but just executes arbitrary commands in a shell.
- `-x` option (analogous to Metasploit) isn't registered and the normal RSF prompt is displayed.

## Expected Behavior

Metasploit has a `-x` option that allows executing modules in scripts.

As an example, `python rsf.py -x "use scanners/autopwn;set target 10.0.0.1;run"` should run everything in a script and display the output instead of an interactive prompt.

Is this possible already with the current version? Thanks!

**Comment by lucyoa** [comment]
Resolves with #556
