### ISSUE TITLE
Can't use command : python3 -m pip install -r requirements.txt .

### ISSUE THREAD

**Issue by noragamirel** [threat9/routersploit#563]
Hello, i'm need your help about this error
When i run :

> root@linux:~/routersploit# python3 -m pip install -r requirements.txt

And this error is appear :

Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1)) (0.16.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (2.20.0)
Requirement already satisfied: paramiko in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2.4.2)
Requirement already satisfied: pysnmp==4.4.6 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (4.4.6)
Requirement already satisfied: pycryptodome in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 5)) (3.6.6)

## Your Environment
* RouterSploit Version used: Latest
* Operating System and version: Linux 32 bit
* Python Version: ( `python3 --version` ) : Python 3.6.8
* Python Environment: ( `python3 -m pip freeze` ) : 
AdvancedHTTPServer==2.0.11
ajpy==0.0.4
alembic==1.0.0.dev0
apipkg==1.5
asn1crypto==0.24.0
atomicwrites==1.2.1
attrs==18.2.0
basemap==1.1.0
bcrypt==3.1.5
beautifulsoup4==4.6.3
binwalk==2.1.2
blinker==1.4
bluepy==1.2.0
boltons==18.0.0
Brlapi==0.6.7
Brotli==1.0.7
certifi==2018.8.24
chardet==3.0.4
chrome-gnome-shell==0.0.0
click==7.0.dev0
cmd2==0.9.6
CoAPthon3==1.0.1
colorama==0.3.7
crcelk==1.3
cryptography==2.3
cupshelpers==1.0
cycler==0.10.0
debtags==2.1
decorator==4.3.0
distro==1.3.0
dnspython==1.16.0
ecdsa==0.13
email-validator==1.0.3
entrypoints==0.2.3
execnet==1.5.0
expliot==0.1.0a1
fake-useragent==0.1.11
Faker==0.9.2
faker-wifi-essid==0.2.0
flake8==3.5.0
Flask==1.0.2
future==0.16.0
fuzzywuzzy==0.17.0
geoip2==2.9.0
geojson==2.4.1
graphene==2.0.1
graphene-sqlalchemy==2.0.0
graphql-core==2.1
graphql-relay==0.4.5
gunicorn==19.9.0
h11==0.8.1
h2==3.0.1
hashID==3.1.4
hpack==3.0.0
html5lib==1.0.1
httplib2==0.11.3
hyperframe==5.1.0
icalendar==4.0.3
idna==2.6
IPy==0.83
iso8601==0.1.11
itsdangerous==0.24
Jinja2==2.10
jsonschema==2.6.0
kaitaistruct==0.8
keyring==17.1.1
keyrings.alt==3.1.1
kiwisolver==1.0.1
ldap3==2.4.1
louis==3.7.0
lxml==4.2.5
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.2.2
maxminddb==1.4.1
mccabe==0.6.1
mitmproxy==4.0.4
more-itertools==4.3.0
msgpack==0.5.6
mysqlclient==1.3.10
netaddr==0.7.19
numpy==1.14.5
olefile==0.46
paho-mqtt==1.4.0
paramiko==2.4.2
passlib==1.7.1
patator==0.7
Pillow==5.3.0
pluggy==0.8.0
pluginbase==0.7
ply==3.11
prettytable==0.7.2
probequest==0.7.0
promise==2.0.1
psycopg2==2.7.6.1
py==1.7.0
pyasn1==0.4.2
pycairo==1.16.2
pycodestyle==2.3.1
pycrypto==2.6.1
pycryptodome==3.6.6
pycryptodomex==3.6.1
pycups==1.9.73
pycurl==7.43.0.1
pyenchant==2.0.0
pyflakes==1.6.0
pyftdi==0.29.2
PyGObject==3.30.4
pygtkspellcheck==4.0.5
pyi2cflash==0.1.1
PyJWT==1.7.0
pymodbus==2.1.0
PyNaCl==1.3.0
PyOpenGL==3.1.0
pyOpenSSL==18.0.0
pyotp==2.2.6
pyparsing==2.2.0
pyperclip==1.6.4
pyproj==1.9.5.1
pyqtgraph==0.10.0
pyserial==3.4
pyshp==2.0.1
PySimpleSOAP==1.16.2
pysmbc==1.0.15.6
pysmi==0.3.2
pysnmp==4.4.6
PySocks==1.6.8
pyspiflash==0.5.2
pytest==3.9.1
pytest-forked==0.2
pytest-xdist==1.23.2
python-apt==1.7.0
python-can==3.0.0
python-dateutil==2.7.5
python-debian==0.1.33
python-debianbts==2.8.2
python-editor==1.0.3
python-Levenshtein==0.12.0
python-pam==1.8.4
pytz==2018.7
pyusb==1.0.2
pyxdg==0.25
PyYAML==3.13
raccoon-scanner==0.8.5
reportbug==7.5.1
requests==2.20.0
requests-file==1.4.3
ruamel.yaml==0.15.34
Rx==1.6.1
scapy==2.4.0
scipy==1.1.0
SecretStorage==2.3.1
six==1.12.0
smoke-zephyr==1.4.0
sortedcontainers==2.0.4
SQLAlchemy==1.2.8
tabulate==0.8.2
termcolor==1.1.0
termineter==1.0.4
text-unidecode==1.2
threat9-test-bed==0.6.1.dev2+g1ed61b3
tld==0.9.1
tornado==5.1.1
typing==3.6.6
tzlocal==1.5.1
unattended-upgrades==0.1
urllib3==1.24
urwid==2.0.1
wafw00f==0.9.5
wapiti3==3.0.1
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.53.0
Werkzeug==0.14.1
wrapt==1.10.11
wsproto==0.11.0
XlsxWriter==0.9.6
xmltodict==0.11.0
yaswfp==0.9.3

Question : What i **_need to do_** with this error ?

**Comment by lucyoa** [comment]
Its not an error. It means that you have all requirements already installed.
