### ISSUE TITLE
run error on Kali Nethunter

### ISSUE THREAD

**Issue by EastwindZL** [threat9/routersploit#567]
## Steps to Reproduce (for bugs)
1.apt-get install routersploit
![screenshot_20190210150636](https://user-images.githubusercontent.com/29472751/52530789-88a4b600-2d45-11e9-8a73-81fbf9fc2cd6.jpg)

## Your Environment
* RouterSploit Version used:3.4.0
* Operating System and version:Linux kali 4.4.78-ElementalX-OP5-3.04 #1 SMP PREEMPT Sat Apr 28 12:07:16 CST 2018 armv8l GNU/Linux
* Python Version: ( `python3 --version` )  3.7.2+
* Python Environment: ( `python3 -m pip freeze` )

root@kali:~# python3 -m pip freeze
asn1crypto==0.24.0
bcrypt==3.1.6
bluepy==1.1.4
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
cryptography==2.3
entrypoints==0.3
future==0.17.1
idna==2.6
input==0.0.0
keyring==17.1.1
keyrings.alt==3.1.1
paramiko==2.4.2
ply==3.11
pyasn1==0.4.5
pycparser==2.19
pycrypto==2.6.1
pycryptodomex==3.6.1
PyGObject==3.30.4
PyNaCl==1.3.0
pysmi==0.3.3
pysnmp==4.4.6
pyxdg==0.25
requests==2.21.0
routersploit==3.4.0
SecretStorage==2.3.1
six==1.12.0
urllib3==1.24.1
root@kali:~#

help me! please

**Comment by pple7000** [comment]
Don't use apt-get install.Use git clone to get latest version.😊😊😊
