### ISSUE TITLE
no module name 'readline'

### ISSUE THREAD

**Issue by jakeyhanna** [threat9/routersploit#575]
so i have this problem with starting up routersploit because whenever i type to open it this appears:

pi@jack1e_hanna:~/routersploit $ sudo python3.6 rsf.py
Traceback (most recent call last):
  File "rsf.py", line 10, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/home/pi/routersploit/routersploit/interpreter.py", line 37, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

and when i try to open it without using python3.6 command it launches fine and let me use a module but then this happens:

ive tried downloading it through everything pip apt-get still nothing 

im running the raspbain OS (since kali linux have errors now and might be why its not working)

i will be thankful for anyway or tip to fix this

thanks :)

**Comment by iamleot** [comment]
Hello @jakeyhanna !
How Python 3.6 was installed?  I think that the readline module is missing and that's usually provided as part of python - but in some package systems - as a possible separate package.

**Comment by lucyoa** [comment]
Incomplete report, closing

**Comment by iamleot** [comment]
Marcin Bury writes:
> Incomplete report, closing

That's probably not a routersploit problem but just a missing
readline module but - anyway - IMHO it would be better to wait
some time and for a feedback from the OP before closing it.

**Comment by lucyoa** [comment]
We would wait for feedback and resolve it if the issue template was filled properly and not completely deleted like in this case. It's just not possible to resolve issues if they don't consist of required information.
