### ISSUE TITLE
Threads get started, then instantly get terminated

### ISSUE THREAD

**Issue by kronakk** [threat9/routersploit#597]
! ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY !

## Steps to Reproduce (for bugs)
1.
2.
3.
4.

## Your Environment
* RouterSploit Version used: 3.4.0
* Operating System and version:Kali Linux (Raspberry Pi 3B+)
* Python Version: ( `python3 --version` ) Python 3.7.3
* Python Environment: ( `python3 -m pip freeze` )
```

argcomplete==1.8.1
argh==0.26.2
asn1crypto==0.24.0
attrs==17.4.0
Automat==0.6.0
backdoor-factory==0.0.0
backports-abc==0.5
beautifulsoup4==4.6.3
blinker==1.4
capstone==3.0.5
certifi==2018.8.24
chardet==3.0.4
click==7.0.dev0
colorama==0.3.7
configobj==5.0.6
configparser==3.5.0b2
constantly==15.1.0
cryptography==2.3
dnslib==0.9.7
dnspython==1.15.0
entrypoints==0.2.3.post3
enum34==1.1.6
Flask==1.0.2
future==0.15.2
html5lib==1.0.1
hyperlink==17.3.1
idna==2.6
impacket==0.9.15
incremental==16.10.1
ipaddress==1.0.17
IPy==0.83
itsdangerous==0.24
Jinja2==2.10
keyring==15.1.0
keyrings.alt==3.1
KismetCaptureFreaklabsZigbee==2018.0.0
KismetCaptureRtl433==2018.0.0
KismetExternal==2018.0.0
kismetlog==2018.0.0
kismetrest==1.0
lxml==4.2.4
MarkupSafe==1.0
msgpack==0.5.6
netaddr==0.7.19
NetfilterQueue==0.6
numpy==1.14.5
olefile==0.45.1
PAM==0.4.2
pathtools==0.1.2
pbkdf2==1.3
pcapy==0.10.8
pefile==2018.8.8
Pillow==5.2.0
protobuf==3.0.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycairo==1.16.2
pycrypto==2.6.1
pygame===1.9.1release
PyGObject==3.30.1
pyinotify==0.9.6
pyOpenSSL==18.0.0
PyRIC==0.1.6.3
pyrtlsdr==0.2.3
pyserial==3.4
pysnmp==4.4.9
pysqlite==1.0.1
python-magic==0.4.16
pyxdg==0.25
PyYAML==3.12
requests==2.18.4
roguehostapd==1.2.3
routersploit==3.4.0
RPi.GPIO==0.6.2
scapy==2.4.0
SecretStorage==2.3.1
service-identity==16.0.0
simplejson==3.15.0
singledispatch==3.4.0.3
six==1.11.0
tornado==4.5.3
Twisted==18.7.0
ua-parser==0.8.0
urllib3==1.22
user-agents==1.1.0
watchdog==0.8.3
webencodings==0.5
Werkzeug==0.14.1
wifiphisher==1.4
zope.interface==4.3.2
```

## Current Behavior
* If describing a bug, tell us what happens instead of the expected behavior
* If suggesting a change/improvement, tell us how it works right now

RouterSploit starts perfectly, i select AutoPwn, set my target as my router ip, and enter "run", threads start, then instantly get terminated without any scanning whatsoever
## Expected Behavior
* If you're describing a bug, tell us what should happen
* If you're suggesting a change/improvement, tell us how it should work
What should happen is, threads start, scan for vulnerabilities,threads get terminated.

i cant use the normal version from the github,
TypeError: '>=' not supported between instances of 'tuple' and 'int'
cause of that
so i did apt-get install routersploit, where the scanning doesnt work.

**Comment by OfficialMuffin** [comment]
Im getting the same error

**Comment by judacr** [comment]
I am having the same issue, just installed RSF on Kali linux using apt-get and the issue is there

**Comment by lucyoa** [comment]
Please try the new version now
