### ISSUE TITLE
Stuck at: Building wheel for pynacl (PEP 517)

### ISSUE THREAD

**Issue by MadKing99** [threat9/routersploit#599]
So I was installing the requirements from requirements.txt and I got stuck at:

Building wheel for pynacl (PEP 517) ....

Same happed with requirements-dev.txt

And when i tried to ignore them and started rsf.py then I got a module not found error 'future' (I tried pip install future) please help me with this. Why am i stuck at 
Building wheel for pynacl (PEP 517)

**Comment by EITS403** [comment]
How did you fix this mistake?
