### ISSUE TITLE
help，Unable to install in termux

### ISSUE THREAD

**Issue by EITS403** [threat9/routersploit#600]
[self.run_command(cmd_name)]                    File "/data/data/com.termux/files/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command                                                   self.distribution.run_command(command)        File "/data/data/com.termux/files/usr/lib/python3.7/distutils/dist.py", line 985, in run_command                                                  cmd_obj.run()                                 File "setup.py", line 159, in run                 raise Exception("ERROR: The 'make' utility is missing from PATH")                           Exception: ERROR: The 'make' utility is missing from PATH                                       ----------------------------------------        ERROR: Failed building wheel for pynacl         Running setup.py clean for pynacl             Successfully built bcrypt cryptography          Failed to build pynacl                          ERROR: Could not build wheels for pynacl which use PEP 517 and cannot be installed directly

Unable to install in termux，help me

**Comment by muketot** [comment]
Use this following commands. It may be help you.

$ apt-get update

$ apt-get install sudo

$ sudo apt-get install git-core

$ git clone https://github.com/reverse-shell/routersploit

$ cd routersploit

$ sudo python ./rsf.py

**Comment by lucyoa** [comment]
Closing since there is no more activity and solution steps were provided.

**Comment by Upanori7** [comment]
still happening to me
