### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by zPrototype** [threat9/routersploit#602]
root@kali:~/Tools/routersploit# python3 -m pip install requirements.txt 
Collecting requirements.txt
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/requirements-txt/

this is what happens when I try to install the requirements.txt

Any help on that?

**Comment by OverlordAdmin** [comment]
First have you run the "sudo apt-get install python3-pip" before running the requirement installation?

Next try running this: "sudo python3 -m pip install -r requirements.txt"

**Comment by lucyoa** [comment]
Closing since there is no more activity and solution steps were provided.
