### ISSUE TITLE
Pip install -r requirements.txt error

### ISSUE THREAD

**Issue by X1nto** [threat9/routersploit#605]
Hello everyone, I'm using termux and can't install routersploit, i have installed requests, but can't install requirements.txt,

Requirement already satisfied: future in /data/data/com.termux/files/usr/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (0.17.1)
Requirement already satisfied: requests in /data/data/com.termux/files/usr/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (2.22.0)           Collecting paramiko (from -r requirements.txt (line 3))                          Using cached https://files.pythonhosted.org/packages/4b/80/74dace9e48b0ef923633dfb5e48798f58a168e4734bca8ecfaf839ba051a/paramiko-2.6.0-py2.py3-none-any.whl Collecting pysnmp==4.4.6 (from -r requirements.txt (line 4))                     Using cached https://files.pythonhosted.org/packages/99/1a/9e0cdf6a963998185eeebc2a3fa368aa448cac73126a98a4cbf7bdfe85c7/pysnmp-4.4.6-py2.py3-none-any.whl   Collecting pycryptodome (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/e2/7b/12f76a8bd427ebc54f24a0df6fd776fda48087d6a9a32ae0dbc3341dac3f/pycryptodome-3.8.2.tar.gz
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /data/data/com.termux/files/usr/lib/python3.7/site-packages (from requests->-r requirements.txt (line 2)) (3.0.4)                                                                    Requirement already satisfied: certifi>=2017.4.17 in /data/data/com.termux/files/usr/lib/python3.7/site-packages (from requests->-r requirements.txt (line 2)) (2019.6.16)                                                                   Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /data/data/com.termux/files/usr/lib/python3.7/site-packages (from requests->-r requirements.txt (line 2)) (1.25.3)                                                 Requirement already satisfied: idna<2.9,>=2.5 in /data/data/com.termux/files/usr/lib/python3.7/site-packages (from requests->-r requirements.txt (line 2)) (2.8)                                                                             Collecting cryptography>=2.5 (from paramiko->-r requirements.txt (line 3))       Using cached https://files.pythonhosted.org/packages/c2/95/f43d02315f4ec074219c6e3124a87eba1d2d12196c2767fadfdc07a83884/cryptography-2.7.tar.gz               Installing build dependencies ... error                                        ERROR: Command errored out with exit status 1:                                  command: /data/data/com.termux/files/usr/bin/python /data/data/com.termux/files/usr/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-rl42l4nl/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.8,!=1.11.3; python_implementation != '"'"'PyPy'"'"''
       cwd: None
  Complete output (67 lines):
  Collecting setuptools>=40.6.0
    Using cached https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/bb/10/44230dd6bf3563b8f227dbf344c908d412ad2ff48066476672f3a72e174e/wheel-0.33.4-py2.py3-none-any.whl
  Collecting cffi!=1.11.3,>=1.8
    Using cached https://files.pythonhosted.org/packages/93/1a/ab8c62b5838722f29f3daffcc8d4bd61844aa9b5f437341cc890ceee483b/cffi-1.12.3.tar.gz
  Collecting pycparser (from cffi!=1.11.3,>=1.8)
    Using cached https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz
  Installing collected packages: setuptools, wheel, pycparser, cffi
    Running setup.py install for pycparser: started
      Running setup.py install for pycparser: finished with status 'done'
    Running setup.py install for cffi: started
      Running setup.py install for cffi: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /data/data/com.termux/files/usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-bbqxyc1c/cffi/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-bbqxyc1c/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-s0_4d90w/install-record.txt --single-version-externally-managed --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-rl42l4nl/overlay --compile
           cwd: /data/data/com.termux/files/usr/tmp/pip-install-bbqxyc1c/cffi/
      Complete output (48 lines):
      unable to execute 'arm-linux-androideabi-clang': No such file or directory
      unable to execute 'arm-linux-androideabi-clang': No such file or directory

          No working compiler found, or bogus compiler options passed to
          the compiler from Python's standard "distutils" module.  See
          the error messages above.  Likely, the problem is not related
          to CFFI but generic to the setup.py of any Python package that
          tries to compile C code.  (Hints: on OS/X 10.8, for errors about
          -mno-fused-madd see http://stackoverflow.com/questions/22313407/
          Otherwise, see https://wiki.python.org/moin/CompLangPython or
          the IRC channel #python on irc.freenode.net.)

          Trying to continue anyway.  If you are trying to install CFFI from
          a build done in a different context, you can ignore this warning.

      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-armv8l-3.7
      creating build/lib.linux-armv8l-3.7/cffi
      copying cffi/vengine_cpy.py -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/model.py -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/commontypes.py -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/error.py -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/backend_ctypes.py -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/cparser.py -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/ffiplatform.py -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/pkgconfig.py -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/vengine_gen.py -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/api.py -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/lock.py -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/__init__.py -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/setuptools_ext.py -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/cffi_opcode.py -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/verifier.py -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/recompiler.py -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/_cffi_include.h -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/parse_c_type.h -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/_embedding.h -> build/lib.linux-armv8l-3.7/cffi
      copying cffi/_cffi_errors.h -> build/lib.linux-armv8l-3.7/cffi
      running build_ext
      building '_cffi_backend' extension
      creating build/temp.linux-armv8l-3.7
      creating build/temp.linux-armv8l-3.7/c
      arm-linux-androideabi-clang -mfloat-abi=softfp -mfpu=vfpv3-d16 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Oz -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Oz -fPIC -I/usr/include/ffi -I/usr/include/libffi -I/data/data/com.termux/files/usr/include/python3.7m -c c/_cffi_backend.c -o build/temp.linux-armv8l-3.7/c/_cffi_backend.o
      unable to execute 'arm-linux-androideabi-clang': No such file or directory
      error: command 'arm-linux-androideabi-clang' failed with exit status 1
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-bbqxyc1c/cffi/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-bbqxyc1c/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/com.termux/files/usr/tmp/pip-record-s0_4d90w/install-record.txt --single-version-externally-managed --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-rl42l4nl/overlay --compile Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python /data/data/com.termux/files/usr/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /data/data/com.termux/files/usr/tmp/pip-build-env-rl42l4nl/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.8,!=1.11.3; python_implementation != '"'"'PyPy'"'"'' Check the logs for full command output.

* Routersploit 3.4.0
* Android 7.1.2
* Python 3.7.4
* certifi==2019.6.16
  chardet==3.0.4
  future==0.17.1
  idna==2.8
  PySocks==1.7.0
  requests==2.22.0
  urllib3==1.25.3
  wget==3.2

Any help?
Thanks.

### **_UPDATE: I have fixed problem by installing unstabel-repo and dev libraries_**.

**Comment by kidBuuReborn** [comment]
im having this same issue but im not understanding your update where you said you fixed this issues, where are those packages when i google ir it tells me many linux libraries but not a dev one

**Comment by x13robotx** [comment]
X1nto

Bro how u fixed it help me
