### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by AlicePlayz** [threat9/routersploit#614]
Why cant i clone the routersploit?? I already done the other steps carefully but why cant it clone? And this happens often with other things i try to install or clone..

$ git clone https://github.com/threat9/routersploit
fatal: could not create work tree dir 'routersploit': No such file or directory

**Comment by 0BuRner** [comment]
https://stackoverflow.com/questions/16376035/fatal-could-not-create-work-tree-dir-kivy
