### ISSUE TITLE
Error code 1 when installing

### ISSUE THREAD

**Issue by kattking16** [threat9/routersploit#617]
! ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY !

## Steps to Reproduce (for bugs)
1.
2.
3.
4.

## Your Environment
* RouterSploit Version used: idk the current one on the github
* Operating System and version:android with kali sub system
* Python Version: (`3.7.4+)
* Python Environment: 
asn1crypto==0.24.0
cryptography==2.6.1
dbus-python==1.2.12
entrypoints==0.3
keyring==18.0.1
keyrings.alt==3.1.1
pycrypto==2.6.1
PyGObject==3.34.0
pyxdg==0.25
SecretStorage==2.3.1
six==1.12.0
## Current Behavior
* If describing a bug, tell us what happens instead of the expected behavior
* If suggesting a change/improvement, tell us how it works right now

## Expected Behavior
* If you're describing a bug, tell us what should happen
* If you're suggesting a change/improvement, tell us how it should work

  ----------------------------------------
Command "/usr/bin/python3 -m pip install --ignore-installed
--no-user --prefix /tmp/pip-build-env-bfvuh0mu --no-warn-scr
ipt-location --no-binary :none: --only-binary :none: -i http
s://pypi.org/simple -- setuptools>=40.8.0 wheel "cffi>=1.1;
python_implementation != 'PyPy'"" failed with error code 1 i
n None

**Comment by lucyoa** [comment]
This is not an issue with routersploit.
