### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by Chr0m0s0m3s** [threat9/routersploit#619]
## Your Environment
* RouterSploit Version used: 3.4.0
* Operating System and version: Windows 10 Pro
* Python Version: 3.7.4
* Python Environment: aiohttp==3.5.4
alabaster==0.7.12
asn1crypto==1.0.1
async-timeout==3.0.1
attrs==19.1.0
Babel==2.7.0
bcrypt==3.1.7
beautifulsoup4==4.7.1
boto3==1.9.236
botocore==1.12.236
bs4==0.0.1
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
chromedriver-binary==78.0.3904.11.0
Click==7.0
cliff==2.16.0
cmd2==0.8.9
colorama==0.4.1
config==0.4.2
configobj==5.0.6
configparser==4.0.2
cryptography==2.7
Deprecated==1.2.6
discord.py==1.2.3
docutils==0.15.2
filelock==3.0.12
Flask==1.0.2
Flask-Login==0.4.1
future==0.17.1
gitdb2==2.0.5
GitPython==3.0.2
gnupg==2.3.1
html5lib==1.0.1
humanfriendly==4.18
idna==2.7
imagesize==1.1.0
importlib-metadata==0.23
inflect==2.1.0
itsdangerous==1.1.0
jaraco.itertools==4.4.2
Jinja2==2.10.1
jmespath==0.9.4
lxml==4.4.1
MarkupSafe==1.1.1
more-itertools==7.2.0
multidict==4.5.2
nmap==0.0.1
numpy==1.17.2
ordered-set==3.1.1
packaging==19.2
paramiko==2.6.0
pbr==5.4.3
pexpect==4.7.0
phonenumbers==8.10.2
Pillow==6.1.0
pluggy==0.13.0
ply==3.11
praw==6.3.1
prawcore==1.0.1
prettytable==0.7.2
property-manager==2.3.1
psutil==5.6.3
ptyprocess==0.6.0
py==1.8.0
pyasn1==0.4.7
pycparser==2.19
pycryptodome==3.9.0
pycryptodomex==3.9.0
pyfiglet==0.8.post1
pyflakes==2.1.1
pygame==1.9.6
PyGithub==1.43.8
Pygments==2.4.2
PyJWT==1.7.1
PyLaTeX==1.3.0
PyNaCl==1.3.0
pyparsing==2.4.2
pyperclip==1.7.0
pyreadline==2.1
pysmi==0.3.4
pysnmp==4.4.6
PySocks==1.7.1
python-dateutil==2.8.0
python-nmap==0.6.1
python-secrets==19.9.0
pytz==2019.2
PyYAML==5.1.2
qrcode==6.1
regex==2019.8.19
requests==2.21.0
requests-futures==1.0.0
s3transfer==0.2.1
selenium==3.141.0
six==1.12.0
smmap2==2.0.5
snowballstemmer==1.9.1
soco==0.11.1
socos==0.2
soupsieve==1.9.3
Sphinx==2.2.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
stem==1.7.1
stevedore==1.31.0
strawpy==1.1
Tokage==1.4
toml==0.10.0
torrequest==0.1.0
tox==3.14.0
update-checker==0.16
urllib3==1.24.3
verboselogs==1.7
virtualenv==16.7.5
webencodings==0.5.1
websocket-client==0.56.0
websockets==6.0
Werkzeug==0.15.6
windows-curses==2.0
wolframalpha==3.0.1
wrapt==1.11.2
xkcdpass==1.17.3
xmltodict==0.12.0
yamlreader==3.0.4
yarl==1.3.0
youtube-dl==2019.9.12.1
zipp==0.6.0

## Current Behavior
libedit fails with the following error :
![image](https://user-images.githubusercontent.com/53451298/66266639-4c2e4900-e845-11e9-8340-a8ad81d07559.png)

## Expected Behavior
module finishes without error

**Comment by FieryRMS** [comment]
Open interpreter.py from "routersploit-master\routersploit" in the IDLE

Searh for the following line
`import readline`

Replace it with the following lines
`from pyreadline import Readline`
`readline = Readline()`

open cmd and type "pip install pyreadline"

Try to open the program now, it should work.
