### ISSUE TITLE
character error

### ISSUE THREAD

**Issue by ortiga88** [threat9/routersploit#640]
![Captura](https://user-images.githubusercontent.com/26000087/72528570-ad65af80-386b-11ea-8704-99799b7838d2.PNG)

the program looks at me with weird characters is there anything to fix it ??

**Comment by Robin6464** [comment]
Try to use cygwin to run routersploit under windows. Make sure you have the required modules, libraries and python3 installed in cygwin. It works for me and I don't have any problems.
