### ISSUE TITLE
Is this a backdoor account in zte zxhn h108n v2.5 router ?

### ISSUE THREAD

**Issue by minanagehsalalma** [threat9/routersploit#649]
i found these when i opened the router config file using router pass view tool from nirsoft.

I can login using the username admin and the blurred password(my password). 
![image](https://user-images.githubusercontent.com/20546638/75123047-b9376380-56ac-11ea-849f-ec974424a28d.png)

But i can't login using these

![image](https://user-images.githubusercontent.com/20546638/75123069-c7857f80-56ac-11ea-89e3-6989d2a21a90.png)

although the enable value = 1
the only difference i see is the app ID What would that be ? Why are they there ?
also this the same in ZXHN H168N V3.1 router too

**Comment by 0BuRner** [comment]
AppID may correspond the credentials listening on other ports (SSH, FTP, ...) or even internal components.

**Comment by minanagehsalalma** [comment]
> AppID may correspond the credentials listening on other ports (SSH, FTP, ...) 


nob not really as you can see in H168N V3.1 config the credentials are different  and already have there own Tbl 
ssh
![image](https://user-images.githubusercontent.com/20546638/75139760-202d3a80-56f6-11ea-89e5-5025afdd5a2f.png)
ftp
![image](https://user-images.githubusercontent.com/20546638/75139936-92058400-56f6-11ea-95ce-9b5ce2471662.png)
telnet 
![image](https://user-images.githubusercontent.com/20546638/75139971-a0ec3680-56f6-11ea-8feb-ee8502dcf8ec.png)
...
when i searched the config file for the word admin i found this
![image](https://user-images.githubusercontent.com/20546638/75140293-3f789780-56f7-11ea-966d-c4e8c7124e71.png)

**Comment by minanagehsalalma** [comment]
@lucyoa so you have no idea about it ?

If we figured out what its for ... it can be used for Authentication bypass.
