### ISSUE TITLE
routersploit segmentation fault

### ISSUE THREAD

**Issue by AlienWolfX** [threat9/routersploit#660]
#Your Environment
* RouterSploit Version used: 3.4.1
* Operating System and version: Kali Linux(Latest)
* Python Version: 3.7.7
* Python Environment: apipkg==1.5
atomicwrites==1.3.0
attrs==19.3.0
bcrypt==3.1.7
bluepy==1.3.0
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
click==7.1.1
cryptography==2.9
entrypoints==0.3
execnet==1.7.1
Faker==4.0.3
flake8==3.7.9
Flask==1.1.2
future==0.18.2
gunicorn==20.0.4
idna==2.8
importlib-metadata==1.6.0
itsdangerous==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
mccabe==0.6.1
more-itertools==8.2.0
paramiko==2.7.1
pluggy==0.13.1
ply==3.11
py==1.8.1
pyasn1==0.4.8
pycodestyle==2.5.0
pycparser==2.20
pycryptodome==3.9.7
pycryptodomex==3.9.7
pyflakes==2.1.1
PyNaCl==1.3.0
pyOpenSSL==19.1.0
pysmi==0.3.4
pysnmp==4.4.6
pytest==4.4.0
pytest-forked==1.1.3
pytest-xdist==1.31.0
python-dateutil==2.8.1
readline==6.2.4.1
requests==2.21.0
six==1.14.0
text-unidecode==1.3
threat9-test-bed==0.6.1.dev2+g1ed61b3
urllib3==1.24.3
Werkzeug==1.0.1
zipp==3.1.0

![Screenshot 2020-04-14 12:09:54](https://user-images.githubusercontent.com/60495687/79185228-4e6cf380-7de4-11ea-8821-2238ad65405c.png)

**Comment by lucyoa** [comment]
I cannot reproduce this. I downloaded fresh kali linux 2020.2 and installed routersploit without issues.

```
sudo apt-get install python3-pip
git clone https://github.com/threat9/routersploit
cd routersploit
python3 m pip install -r requirements.txt
python3 rsf.py
```

**Comment by marcus686** [comment]
Not working on TERMUX?

**Comment by AlienWolfX** [comment]
Sorry for the late reply I got it working by updating some packages. Thank you
