### ISSUE TITLE
No target options in Routersploit

### ISSUE THREAD

**Issue by Ratnesh2003** [threat9/routersploit#667]
## I installed Routersploit on termux on my android 10 device. Installation was perfectly completed. Whenever I use the command 
`use scanners/autopwn`
Then 
`show options`
After this I see no available devices. 
![Screenshot_20200521-170101](https://user-images.githubusercontent.com/65713765/82555131-d339f280-9b84-11ea-8f00-2b0b4d1ef6b5.png)

## Your Environment
* RouterSploit Version used: 3.4.1
* Operating System and version: Anroid 10
* Python Version: `python3`

I have met all the requirements for routersploit. 
Thanks in advance...

**Comment by lucyoa** [comment]
I'm confused. Once you choose `scanner/autopwn` you should specify target IP address and type `run`. The autopwn module will start scanning device and idenitify vulnerabilities.

**Comment by lucyoa** [comment]
I'm closing since im not getting response.
