### ISSUE TITLE
ModuleNotFoundError: No module named 'readline'

### ISSUE THREAD

**Issue by KeeperLifeblood** [threat9/routersploit#668]
! ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY !

## Steps to Reproduce (for bugs)
1. open de cmd
2. run python3 rsf.py
3.appears that error:   File "rsf.py", line 10, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "C:\Users\Marco\Desktop\routersploit-master\routersploit\interpreter.py", line 38, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
4.

## Your Environment 
* RouterSploit Version used:  the last 
* Operating System and version: Win 10
* Python Version: ( `python3 --3.8.` )
* Python Environment: ( `python3 -m pip last` )

## Current Behavior
Im try to run the rsf.py and appear that error:

  File "rsf.py", line 10, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "C:\Users\Marco\Desktop\routersploit-master\routersploit\interpreter.py", line 38, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

**Comment by MOSTAFAABOELNOUR** [comment]
try this 
```
sudo pip install readline
```

**Comment by finleyzinser** [comment]
@MOSTAFAABOELNOUR the same thing happened to me, expect this didnt fix it, i only got another error saying:


$ python -m pip install readline
Collecting readline
  Using cached readline-6.2.4.1.tar.gz (2.3 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TEMP.LAPTOP-IM26HHKE\\AppData\\Local\\Temp\\pip-install-kwafbs6w\\readline\\setup.py'"'"'; __file__='"'"'C:\\Users\\TEMP.LAPTOP-IM26HHKE\\AppData\\Local\\Temp\\pip-install-kwafbs6w\\readline\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\TEMP.LAPTOP-IM26HHKE\AppData\Local\Temp\pip-pip-egg-info-hdf1bg3v'
         cwd: C:\Users\TEMP.LAPTOP-IM26HHKE\AppData\Local\Temp\pip-install-kwafbs6w\readline\
    Complete output (1 lines):
    error: this module is not meant to work on Windows
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


....
I dont know what to do or where to go from here

**Comment by algorithmx51** [comment]
try this :
https://stackoverflow.com/questions/6622490/ipython-no-readline-available-and-pip-install-readline-error

**Comment by adarshadhungel1** [comment]
`pip install pyreadline`
should do the job

**Comment by binarioGH** [comment]
Since you are on windows, try `pip install pyreadline` its like readline, but written in python.
