### ISSUE TITLE
munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by Espinosa123321** [threat9/routersploit#671]
! ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY !

## Steps to Reproduce (for bugs)
1.python3 rsf.py
2.rsf > use scanners/autopwn
   munmap_chunk(): invalid pointer
   Aborted

## Your Environment
* RouterSploit Version used:3.4.2
* Operating System and version:Kali Linux 2020.2
* Python Version: 3.8.3
* Python Environment:
AccessControl==4.2
Acquisition==4.6
apipkg==1.5
appdirs==1.4.4
atomicwrites==1.4.0
attrs==19.3.0
AuthEncoding==4.1
Automat==20.2.0
bcrypt==3.1.7
beautifulsoup4==4.9.1
blinker==1.4
bluepy==1.3.0
Brotli==1.0.7
bs4==0.0.1
BTrees==4.7.2
capstone==4.0.2
certifi==2020.4.5.1
cffi==1.14.0
Chameleon==3.7.1
chardet==3.0.4
click==7.1.2
configobj==5.0.6
constantly==15.1.0
cryptography==2.9.2
DateTime==4.3
distlib==0.3.0
dnslib==0.9.12
dnspython==1.16.0
dnstwist==20200521
DocumentTemplate==3.2.3
execnet==1.7.1
ExtensionClass==4.4
Faker==4.1.0
filelock==3.0.12
flake8==3.8.2
Flask==1.1.2
future==0.18.2
gunicorn==20.0.4
h11==0.9.0
h2==3.2.0
h8mail==2.5.2
hpack==3.0.0
hyperframe==5.2.0
hyperlink==19.0.0
idna==2.8
incremental==17.5.0
IPy==1.0
itsdangerous==1.1.0
Jinja2==2.11.2
kaitaistruct==0.8
ldap3==2.7
lxml==4.5.1
MarkupSafe==1.1.1
mccabe==0.6.1
mitmproxy==5.1.1
more-itertools==8.3.0
msgpack-python==0.5.6
MultiMapping==4.1
netaddr==0.7.19
NetfilterQueue @ git+https://github.com/kti/python-netfilterqueue@ec2ae290667b2d3f09d5ec1278d899db2f08c52f
netifaces==0.10.9
nmap==0.0.1
packaging==20.4
paramiko==2.7.1
passlib==1.7.2
PasteDeploy==2.1.0
pbr==5.4.5
pefile==2019.4.18
Persistence==3.0
persistent==4.6.4
pexpect==4.8.0
Pillow==7.1.2
pluggy==0.13.1
ply==3.11
protobuf==3.11.3
ptyprocess==0.6.0
publicsuffix2==2.20191221
py==1.8.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.6.0
pycparser==2.20
pycrypto==2.6.1
pycryptodome==3.9.7
pycryptodomex==3.9.7
pyflakes==2.2.0
PyHamcrest==2.0.2
pyinotify==0.9.6
PyNaCl==1.4.0
pynotify==0.1.1
pyOpenSSL==19.1.0
pyparsing==2.4.7
pypcap==1.2.3
pyperclip==1.8.0
pysmi==0.3.4
pysnmp==4.4.6
pytest==4.4.0
pytest-forked==1.1.3
pytest-xdist==1.32.0
python-dateutil==2.8.1
python-gettext==4.0
python-magic==0.4.18
python-nmap==0.6.1
pytz==2020.1
readline==6.2.4.1
requests==2.21.0
RestrictedPython==5.0
roman==3.2
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
scapy==2.4.3
service-identity==18.1.0
six==1.15.0
sortedcontainers==2.1.0
soupsieve==2.0.1
stevedore==1.32.0
termcolor==1.1.0
text-unidecode==1.3
threat9-test-bed @ git+git://github.com/threat9/threat9-test-bed@1ed61b34d0b138711e3f8267259cdb29787fe349
tornado==6.0.4
transaction==3.0.0
Twisted==20.3.0.dev0
ua-parser==0.10.0
urllib3==1.24.3
urwid==2.1.0
user-agents==2.1
virtualenv==20.0.21
virtualenv-clone==0.5.4
virtualenvwrapper==4.8.4
waitress==1.4.3
wcwidth==0.1.9
WebOb==1.8.6
WebTest==2.0.35
Werkzeug==1.0.1
WSGIProxy2==0.4.6
wsproto==0.15.0
z3c.pt==3.3.0
zc.lockfile==2.0
ZConfig==3.5.0
zExceptions==4.1
ZODB==5.5.1
zodbpickle==2.0.0
Zope==4.4.2
zope.annotation==4.7.0
zope.browser==2.3
zope.browsermenu==4.4
zope.browserpage==4.4.0
zope.browserresource==4.4
zope.cachedescriptors==4.3.1
zope.component==4.6.1
zope.configuration==4.4.0
zope.container==4.4.0
zope.contentprovider==4.2.1
zope.contenttype==4.5.0
zope.deferredimport==4.3.1
zope.deprecation==4.4.0
zope.dottedname==4.3
zope.event==4.4
zope.exceptions==4.3
zope.filerepresentation==5.0.0
zope.globalrequest==1.5
zope.hookable==5.0.1
zope.i18n==4.7.0
zope.i18nmessageid==5.0.1
zope.interface==5.1.0
zope.lifecycleevent==4.3
zope.location==4.2
zope.pagetemplate==4.5.0
zope.processlifetime==2.3.0
zope.proxy==4.3.5
zope.ptresource==4.2.0
zope.publisher==5.2.0
zope.schema==6.0.0
zope.security==5.1.1
zope.sequencesort==4.1.2
zope.site==4.3.0
zope.size==4.3
zope.structuredtext==4.3
zope.tal==4.4
zope.tales==5.0.2
zope.testbrowser==5.5.1
zope.testing==4.7
zope.traversing==4.4.1
zope.viewlet==4.2.1
zstandard==0.13.0 

## Current Behavior
I can't use anything because of the munmap_chunk(): invalid pointer

**Comment by DasPinguinHD** [comment]
Same issue, I just wanted to start with this Tool.....

**Comment by Espinosa123321** [comment]
@DasPinguinHD can you fix it?

**Comment by DasPinguinHD** [comment]
Sadly not thars why I wrote this... Sorry...

**Comment by DasPinguinHD** [comment]
So now I have followed the install instruction and now it works. How are you trying to execute Routersploit?

**Comment by DasPinguinHD** [comment]
> @DasPinguinHD can you fix it?

Maybe. So now I have followed the install instruction and now it works. How are you trying to execute Routersploit?

**Comment by Espinosa123321** [comment]
@DasPinguinHD 
i followed the instructions but some modules are not installed so i used python -m pip install (the module)

**Comment by lucyoa** [comment]
I cannot reproduce this behaviour. I just downloaded fresh kali linux and installed routersploit on it without any issues.

**Comment by DasPinguinHD** [comment]
yea exactly. I followed the install instructions and now it works, I already wrote that, but why did u add this "cant reproduce" label? I was just waiting for an answer from @Espinosa123321. I had the same issue and fixed it, so please, if you dont know what it is and someone is already helping, you dont need to write anything.

**Comment by Espinosa123321** [comment]
@DasPinguinHD @lucyoa thank for the help, I have already fixed it, btw can you help me in other issue

**Comment by DasPinguinHD** [comment]
Yea sure, tell us. It just depends on what it is :)

**Comment by Espinosa123321** [comment]
its in here https://github.com/aircrack-ng/rtl8188eus/issues/57
