### ISSUE TITLE
module Not Found error

### ISSUE THREAD

**Issue by tpworld** [threat9/routersploit#683]
$ python3 rsf.py
Traceback (most recent call last):
  File "rsf.py", line 10, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/data/data/com.termux/files/home/routersploit/routersploit/interpreter.py", line 12, in <module>
    from future.builtins import input
ModuleNotFoundError: No module named 'future'

**Comment by lucyoa** [comment]
The report template its here for a reason. Please fill it properly, otherwise we are not able to help you.

**Comment by davidferraz01** [comment]
I had this same issue, even with the future module already installed. I just cd into /routersploit/routersploit/ and run "pip install future". Worked for me. I hope that helps you!

**Comment by bennova5** [comment]
not work
