### ISSUE TITLE
Error during loading 'routersploit/modules/scanners/outopwn'  Error: No module named 'routersploit.modules.scanners.outopwn'

### ISSUE THREAD

**Issue by hkgururaj** [threat9/routersploit#694]
! ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY !

## Steps to Reproduce (for bugs)
1.
2.
3.
4.

## Your Environment
* RouterSploit Version used:
* Operating System and version:
* Python Version: ( `python3 --version` )
* Python Environment: ( `python3 -m pip freeze` )

## Current Behavior
* If describing a bug, tell us what happens instead of the expected behavior
* If suggesting a change/improvement, tell us how it works right now

## Expected Behavior
* If you're describing a bug, tell us what should happen
* If you're suggesting a change/improvement, tell us how it should work

**Comment by GILLESMaster** [comment]
For me routersploit works just fine.
I am going to see if I can send the build
