### ISSUE TITLE
Error no module named future

### ISSUE THREAD

**Issue by ahmad092828** [threat9/routersploit#695]

**Comment by algorithmx51** [comment]
future is a python library, install with:
pip3 install future

**Comment by davidferraz01** [comment]
I had this same issue, even with the future module already installed. I just cd into "/routersploit/routersploit/" and run "pip install future". Worked for me. 
I hope that helps you!

**Comment by algorithmx51** [comment]
Also try to run "sudo pip3 install future" , since you run python3 rsf.py as root

**Comment by puffpuffg1ve** [comment]
I can't install future idk why



WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.


My setup : Samsung Galaxy S10e 
Termux (F-Droid)
OS: Android 12
