### ISSUE TITLE
RouterSploit not working for Mac OS Catalina

### ISSUE THREAD

**Issue by letsmakesenseofthis** [threat9/routersploit#702]
! ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY !

## Steps to Reproduce (for bugs)
1.open terminal
2. cd RouterSploit
3. cd: no such file or directory: routersploit
4. sudo python3 ./rsp.
5. password prompt
6. /Library/Frameworks/Python.framework/Versions/3.8/bin/python3: can't open file './rsp.': [Errno 2] No such file or directory

## Your Environment
* RouterSploit Version used: not sure
* Operating System and version: MacOs 10.15.6
* Python Version: ( `python3 --version` )
* Python Environment: ( `python3 -m pip freeze` )

## Current Behavior
* Terminal won't run RouterSploit
* If suggesting a change/improvement, tell us how it works right now

## Expected Behavior
* If you're describing a bug, tell us what should happen
* If you're suggesting a change/improvement, tell us how it should work

**Comment by Thman558** [comment]
make sure to git clone Routersploit so it gets saved to your home dir
python3 rsf.py

**Comment by letsmakesenseofthis** [comment]
Figured the problem was I need to install python first 🤦‍♂️ I’m new
