### ISSUE TITLE
Errorr ?? 

### ISSUE THREAD

**Issue by younotknowme** [threat9/routersploit#709]
![Screenshot_2020-11-01-19-53-20-988_com termux](https://user-images.githubusercontent.com/73782609/97803577-dcbf9e80-1c7c-11eb-8280-1068e27592f0.jpg)

**Comment by younotknowme** [comment]
![Uploading Screenshot_2020-11-01-20-01-34-352_com.termux.jpg…]()

**Comment by younotknowme** [comment]
![Screenshot_2020-11-01-20-01-34-352_com termux](https://user-images.githubusercontent.com/73782609/97803631-3e800880-1c7d-11eb-8d6e-3556f38a04ac.jpg)

**Comment by blackdiamond1982** [comment]
Got the same error here... personally I upgraded python from 3.8 to 3.9...maybe this error can be link with that?

**Comment by Mrclown28** [comment]
Ya thank it work

Pada tanggal Sen, 18 Jan 2021 03.49, blackdiamond1982 <
notifications@github.com> menulis:

**Comment by fwkz** [comment]
fixed by #712
