### ISSUE TITLE
I could install the requirments now after the command

### ISSUE THREAD

**Issue by Splendid-star** [threat9/routersploit#740]
I could install the requirments now after the command
```
pkg install libcrypt-dev python-dev
```
you can add that to the Readme.md file to make users able to run it on android

_Originally posted by @D4Vinci in https://github.com/threat9/routersploit/issues/445#issuecomment-393204227_

**Comment by lucyoa** [comment]
There is too many platforms to support everything. Feel free to contribute and add README instructions to make it run on Android.
