### ISSUE TITLE
RoutersploitTermux

### ISSUE THREAD

**Issue by KotMilkMeoW** [threat9/routersploit#745]
! ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY !

## Steps to Reproduce (for bugs)
1. ~ $ dpkg -i openssl_1.1.1-2_arm.deb
dpkg -i openssl-dev_1.1.1-2_arm.deb
dpkg -i openssl-tool_1.1.1-2_arm.deb
dpkg: warning: downgrading openssl from 1.1.1k-2 to 1.1.1-2
(Reading database ... 12909 files and directories currently installed.)
Preparing to unpack openssl_1.1.1-2_arm.deb ...
Unpacking openssl:arm (1.1.1-2) over (1.1.1k-2) ...
dpkg: dependency problems prevent configuration of openssl:arm:
 openssl:arm depends on ca-certificates.

dpkg: error processing package openssl:arm (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 openssl:arm
Selecting previously unselected package openssl-dev:arm.
(Reading database ... 12797 files and directories currently installed.)
Preparing to unpack openssl-dev_1.1.1-2_arm.deb ...
Unpacking openssl-dev:arm (1.1.1-2) ...
dpkg: dependency problems prevent configuration of openssl-dev:arm:
 openssl-dev:arm depends on openssl; however:
  Package openssl:arm is not configured yet.

dpkg: error processing package openssl-dev:arm (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 openssl-dev:arm
Selecting previously unselected package openssl-tool:arm.
(Reading database ... 12905 files and directories currently installed.)
Preparing to unpack openssl-tool_1.1.1-2_arm.deb ...
Unpacking openssl-tool:arm (1.1.1-2) ...
dpkg: error processing archive openssl-tool_1.1.1-2_arm.deb (--install):
 trying to overwrite '/data/data/com.termux/files/usr/etc/tls/openssl.cnf', which is also in package openssl:arm 1.1.1-2
Errors were encountered while processing:
 openssl-tool_1.1.1-2_arm.deb
~ $

## Your Environment
* RouterSploit Version used: last
* Operating System and version: Havos 3.3 android 10
* Python Version: ( `python3 --version` ) 3.9.5
* Python Environment: ( `python3 -m pip freeze` ) ~ $ python3 -m pip freeze
aiohttp==3.7.4.post0
async-timeout==3.0.1
attrs==21.2.0
certifi==2021.5.30
chardet==4.0.0
discord==1.0.1
discord.py==1.7.3
future==0.18.2
idna==2.10
multidict==5.1.0
psutil==5.8.0
requests==2.25.1
typing-extensions==3.10.0.0
urllib3==1.26.6
yarl==1.6.3

**Comment by TormentedSoul666** [comment]
The majority of Python socket based tools doesn't work on embedded devices/IoTs.
Your best options are busybox and/or a C cross-compiler.
