### ISSUE TITLE
Inappropriate ioctl for device

### ISSUE THREAD

**Issue by BananaGeneral** [threat9/routersploit#752]
## Steps to Reproduce (for bugs)
1. `python3 rsf.py`

## Your Environment
* RouterSploit Version used: 3fd3946
* Operating System and version: macOS 10.15.7
* Python Version: Python 3.9.2
* Python Environment: 
bcrypt==3.2.0
beautifulsoup4==4.9.3
bs4==0.0.1
certifi==2021.5.30
cffi==1.14.6
chardet==3.0.4
charset-normalizer==2.0.4
colorama==0.4.4
cryptography==3.4.7
future==0.18.2
idna==2.8
lxml==4.6.3
paramiko==2.7.2
ply==3.11
pyasn1==0.4.8
pycparser==2.20
pycryptodome==3.10.1
pycryptodomex==3.10.1
PyNaCl==1.4.0
pysmi==0.3.4
pysnmp==4.4.6
PySocks==1.7.1
requests==2.21.0
requests-futures==1.0.0
six==1.16.0
soupsieve==2.2.1
stem==1.8.0
torrequest==0.1.0
urllib3==1.24.3

## Current Behavior
* The program doesn't run, instead it throws this error (weather as sudo or not):

```
sh-3.2# python3 rsf.py 
Traceback (most recent call last):
  File "/Users/MyUser/routersploit/rsf.py", line 29, in <module>
    routersploit(sys.argv)
  File "/Users/MyUser/routersploit/rsf.py", line 21, in routersploit
    rsf = RoutersploitInterpreter()
  File "/Users/MyUser/routersploit/routersploit/interpreter.py", line 211, in __init__
    super(RoutersploitInterpreter, self).__init__()
  File "/Users/MyUser/routersploit/routersploit/interpreter.py", line 51, in __init__
    self.setup()
  File "/Users/MyUser/routersploit/routersploit/interpreter.py", line 67, in setup
    readline.read_history_file(self.history_file)
OSError: [Errno 25] Inappropriate ioctl for device
```

## Expected Behavior
* Program should initialize normally.

**Comment by ariyako** [comment]
got the same problem

**Comment by Gugufae** [comment]
Any developments on this?

**Comment by gleb4inka** [comment]
@BananaGeneral 

1. `pip install gnureadline`
2. edit `routersploit/interpreter.py`:

`import readline` to  `import gnureadline as readline`
