### ISSUE TITLE
git tags not pushed in sync to pypi

### ISSUE THREAD

**Issue by anthraxx** [threat9/routersploit#756]
## Current Behavior
* Currently releases seem to exclusively be pushed to pypi where 6.0 is available: https://pypi.org/project/routersploit/#files

## Expected Behavior
* It would be awesome to have git tags in sync so pypi releases can easily be mapped to a very specific commit

thank you very much

**Comment by anthraxx** [comment]
gentle bump @fwkz @lucyoa

**Comment by dvzrv** [comment]
Hi! On Arch Linux we are still on version 3.4.0 (which is from 2018) while on PyPI version 6.0 (from 2021) is available.

Can you please tag and create a new release? :pray:

**Comment by lucyoa** [comment]
I've contacted the maintainer of pypi's routersploit package and requested a transfer. There was never version "6.0" of routersploit.

**Comment by lucyoa** [comment]
Resolved
