### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by azofficial** [threat9/routersploit#772]
I get this error in termux 
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/routersploit/rsf.py", line 10, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/data/data/com.termux/files/home/routersploit/routersploit/interpreter.py", line 12, in <module>
    from future.builtins import input
ModuleNotFoundError: No module named 'future'

* RouterSploit Version 3.4.0
* Operating System termux android
* Python Version: ( 3.10.1 )
* Python Environment: ( I don't know )

**Comment by azofficial** [comment]
Pleads help

**Comment by azofficial** [comment]
Pleass help

**Comment by GH0st3rs** [comment]
Hi, just try it:
`python3 -m pip install -r requirements.txt`

**Comment by 69420plss** [comment]
It dosent work

**Comment by storenth** [comment]
same error

**Comment by Robin6464** [comment]
additional packages that must be installed in termux:

pip3 install future
pkg install rust

**Comment by 69420plss** [comment]
I'll try it thank you
