### ISSUE TITLE
routersploit error

### ISSUE THREAD

**Issue by Navneetpathak12** [threat9/routersploit#792]
It shows can install package cryptography because rust is not present what to do

**Comment by Alekc74** [comment]
> It shows can install package cryptography because rust is not present what to do


1 pip install wheel
2 pkg install rust
3 export CARGO_BUILD_TARGET="$(rustc -Vv | grep "host" | awk '{print $2}')"
4 pip install cryptography

**Comment by Omidghahremani** [comment]
Can u hack this Instagram profile?

Saeedeh.ahmadi_
