### ISSUE TITLE
Kali linux Routersploit not working 

### ISSUE THREAD

**Issue by 69420plss** [threat9/routersploit#799]
step 1: use kali linux in a virtual machine
step 2: type sudo apt install routersploit
step 3: open routersploit and type use scanners/autopwn
step 4: do set target 192.168.1.1
step 5: so run
 RouterSploit Version used: 3.4.1
Enviroment: Virtualbox Kali linux 32Bit
* Python Version: 3.11.2

**Comment by darksoilder** [comment]
what's the error? whats happening please describe

**Comment by coolst3r** [comment]
https://github.com/threat9/routersploit/issues/808
